# Generated by Django 6.0 on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0054_bookmarkbundle_filter_shared_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmarkbundle",
            name="search_params",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
